### ISSUE TITLE
Timeline duplication

### ISSUE THREAD

**Issue by bryanmlyr** [Alexays/Epiboard#19]
![screenshot from 2018-04-24 10-42-29](https://user-images.githubusercontent.com/25261144/39176345-e1c89e4c-47ac-11e8-9025-016a6027060e.png)
When I click on the timeline button a new calendar container appear in the modal window.

Version: Firefox 59.0.2 - built with npm manually

**Comment by Alexays** [comment]
Ui

**Comment by Alexays** [comment]
Fix in c56d46b78aa0fd2cbdee0b313bc4d526264b7d6e
