### ISSUE TITLE
Choose new font

### ISSUE THREAD

**Issue by MrMilon** [Alexays/Epiboard#54]
Hello guys !

What do you think about making the possibilities to change the default font of the extension ?

With a Google Font service support ?
And why not give the possibilities to use a local font ?

Thanks bro' 😄

**Comment by Alexays** [comment]
Offers the user to choose the font of his system in d6cb7171d89273f3398d8e054445de855930e8d6

**Comment by Alexays** [comment]
Can choose custom font in 7d082748b3e57b88bf9b2011c9a1a4e37fe913bd
