### ISSUE TITLE
[Request] Bookmarks

### ISSUE THREAD

**Issue by rayman89** [Alexays/Epiboard#57]
Can you add a section where you can select a bookmark folder and it will show all the bookmarks it has on it and the subfolders as well?

**Comment by Alexays** [comment]
Do you have any idea how to display this, like a list or a grid ?

**Comment by rayman89** [comment]
A grid with a big favicon and bookmark name under it would be nice. In case the title is to big hovering the mouse over it could show the full title. Maybe there could be an option to choose the favicon size and the grid would adjust accordingly so that it can suit people with different amount of bookmarks. In case a favicon is missing there could be an icon that replaces the missing favicon or if possible what would be better would be to have and icon that is a letter with some solid color background that corresponds to the first letter after of the url something like this 

![image](https://user-images.githubusercontent.com/5449042/43486536-b967f464-94d9-11e8-92c4-62fce83d85a3.png)

**Comment by Alexays** [comment]
For the grid having big icons is going to be complicated since sites have 32px or 16px icons, I will do some tests as soon as i can

**Comment by Alexays** [comment]
I have so far implemented as a list and I will make it possible to choose as a list or grid (if possible with icons size) and be able to add a folder as a tab.
It's good for you as an idea ? :smile: 

![screenshot_2018-08-01-11 59 54](https://user-images.githubusercontent.com/13947260/43515378-9e22fe52-9582-11e8-9278-a4800c6ea5cd.png)
![screenshot_2018-08-01-12 00 02](https://user-images.githubusercontent.com/13947260/43515383-a03e525e-9582-11e8-85d0-f1929f0380c3.png)
![screenshot_2018-08-01-12 00 10](https://user-images.githubusercontent.com/13947260/43515385-a1d8aace-9582-11e8-9f7c-7484605b3cfe.png)

**Comment by rayman89** [comment]
Thats really nice too thank you. Suits better the rest of the UI. What about though instead of showing the date there to show the tags?

**Comment by Alexays** [comment]
There is currently no possibility with the API
Issue tracked here https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

**Comment by Alexays** [comment]
Done implementaion in 75e60535fea62fed48636b0aad3921d10fbb5bb5
Will be in next update :smile:
