### ISSUE TITLE
Weather widget should support city IDs as well as names

### ISSUE THREAD

**Issue by V13Axel** [Alexays/Epiboard#59]
I live in a city that returns multiple results under Open Weather Map.

Simply typing in the name provides incorrect results - Showing another location with the same name.

Suggestion: It would be incredible if I could just enter the OWM City ID in place of the city name. 

The widget currently calls `?q=[city name]` on the API when location isn't auto-set. Allowing IDs is as easy as changing the call to `?ID=[ID]` if an ID is entered instead of a city name, would love to see that added.

**Comment by Alexays** [comment]
Done I added it in d94784bde4c142a69bb552e581eecf52d10b8244 :+1:
