### ISSUE TITLE
Right-to-left trends

### ISSUE THREAD

**Issue by ctlaltdefeat** [Alexays/Epiboard#65]
Hi, liking Epiboard!
A minor improvement that would help me would be to fix the trend suggestions that show up in a RTL language (Hebrew, Arabic, etc.) to actually show up as RTL.

**Comment by Alexays** [comment]
Thanks for using Epiboard :100: 
It's simple enough I'll do it by the next update :)

**Comment by Alexays** [comment]
Done in 45e7c30f5df4734db6b1bbf5ec2a1053e586159a
