### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ctlaltdefeat** [Alexays/Epiboard#68]
I'm not at all sure that something like this can be influenced or if it's down to the libraries/frameworks used, but responsiveness and fluidity of animations seem sub-par overall.

It's hard to quite quantify, but a small usecase is switching between the tabs of the "Sessions" cards. 
On a laptop with a i5-8250U, navigating doesn't feel smooth overall.
With a desktop i5-6600k the situation is improved somewhat, but still evident lag.

Note that this is a relatively minor issue.

**Comment by Alexays** [comment]
The performance problem for the session card tabs probably comes from the fact that all the tabs except the first one are loaded only when they are going to be displayed.
I'll try to see if I can improve it

**Comment by ColinMcNeil** [comment]
All the performance issues seem to be when data is populated on the cards. That's a lot of DOM changes happening at once. Maybe use async code?

**Comment by Alexays** [comment]
I found a performance problem, every time DOM updates all the translations reloads which causes a big change to DOM, there are ways to fix this, I'll implement it a max

**Comment by Alexays** [comment]
@ctlaltdefeat Can you check on last version (1.6.1) if it's better ?

**Comment by ctlaltdefeat** [comment]
Yes, it's better. Thanks
