### ISSUE TITLE
Rss feed requires api key

### ISSUE THREAD

**Issue by mauriceoegerli** [Alexays/Epiboard#81]
## Current Behavior
The API api.rss2json.com for converting an rss feed to json gets a http error 429 saying an API key is required.

## Possible Solution
Let us submit our own api key

## Steps to Reproduce (for bugs)
Loading Epiboard with the rss card gets
![grafik](https://user-images.githubusercontent.com/15955392/48397417-dd706a80-e71d-11e8-888d-a279625d064d.png)
And the request gets http error 429
{"status":"error","message":"You are converting new feeds in a very short period, please use an API key (https://rss2json.com/docs)."}

## Your Environment
* Version used: 1.6.2
* Browser Name and version: Firefox 63.0.1
* Operating System and version: Windows 10 Enterprise 1803

**Comment by Alexays** [comment]
Yeah, maybe the best solution is to have an home made XML RSS parser, I'll look on it !

**Comment by Alexays** [comment]
You can now specify api key in b6ff5357ed8d9786f25b24c4bd761f06559c3997

**Comment by ess4654** [comment]
I tried the API key and it still gives 429 error I also included the feeds urls in the settings and it still doesnt work

**Comment by ess4654** [comment]
Whoops never mind its api_key not apikey
