### ISSUE TITLE
First sync not allowing permissions

### ISSUE THREAD

**Issue by Psykar** [Alexays/Epiboard#90]
## Expected Behavior
After installing the extension on one computer, opening the browser on another computer (using the same account) should allow the permission prompts to be accepted.

## Current Behavior
The permission prompts appear, but are all stacked on top of each other, none are clickable, and CPU on the tab maxes out.

## Your Environment

* Version used: 1.7.2
* Browser Name and version: google-chrome-stable
* Operating System and version: ArchLinux
![image](https://user-images.githubusercontent.com/817933/63251995-1f7e9c00-c2ae-11e9-9e57-cf06673909fd.png)

**Comment by Alexays** [comment]
That's a vuetify issue it'll be fixed in next version :)

**Comment by Alexays** [comment]
Fixed with latest release :)
